name: Main Integration

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "CODEOWNERS"
      - "sec-scanners-config.yaml"
      - ".github/**" #Ignoring since build job isn't triggered on the workflow directory changes
      - "external-images.yaml"
    branches:
      - main
      - store-logs-fix
  schedule:
    - cron: '0 5 * * *' # Run every day at 05:00 AM

jobs:
  custom-domain-integration-gcp:
    name: Custom domain integration GCP
    runs-on: ubuntu-latest
    # The additional if is required, because there are optional jobs
    if: ${{ always() && !failure() && !cancelled() }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: ./.github/actions/integration-test-gardener
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manager_image: "europe-docker.pkg.dev/kyma-project/prod/api-gateway/releases/api-gateway-manager:2.10.0"
          gardener_secret: ${{ secrets.GARDENER_TOKEN }}
          gardener_provider: gcp
          dns_secret_json: ${{ secrets.DNS_SECRET_JSON }}

  custom-domain-integration-aws:
    name: Custom domain integration AWS
    runs-on: ubuntu-latest
    # The additional if is required, because there are optional jobs
    if: ${{ always() && !failure() && !cancelled() }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: ./.github/actions/integration-test-gardener
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manager_image: "europe-docker.pkg.dev/kyma-project/prod/api-gateway/main/api-gateway-manager:2.10.0"
          gardener_secret: ${{ secrets.GARDENER_TOKEN }}
          gardener_provider: aws
          dns_secret_json: ${{ secrets.DNS_SECRET_JSON }}
