name: Post Main Workflow

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "CODEOWNERS"
      - "sec-scanners-config.yaml"
      - "external-images.yaml"
    branches:
      - main

jobs:

  migration-downtime-tests-aws:
    name: Zero Downtime Migration Tests AWS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        handler: [ "no_auth", "allow", "noop", "jwt", "oauth2_introspection" ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/e2e-test-gardener
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manager_image: "europe-docker.pkg.dev/kyma-project/prod/api-gateway/main/api-gateway-manager:757f33f45845a65e14ac6508b0e4efeb59b829f7"
          gardener_secret: ${{ secrets.GARDENER_TOKEN }}
          gardener_project_name: ${{ vars.GARDENER_PROJECT_NAME }}
          gardener_provider: aws
          test_client_id: ${{ secrets.CLIENT_ID }}
          test_client_secret: ${{ secrets.CLIENT_SECRET }}
          test_oidc_well_known_url: "${{ secrets.OIDC_ISSUER_URL }}/.well-known/openid-configuration"
          test_make_target: test-migration-zero-downtime-${{ matrix.handler }}
