name: Release Api Gateway

permissions:
  id-token: write # This is required by image-builder
  contents: write # Read is required by image-builder, write is required to push artifact

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        default: ""
        required: true

env:
  image-name: "europe-docker.pkg.dev/kyma-project/prod/api-gateway/releases/api-gateway-manager"

jobs:
  check-prerequisites: 
    name: Check prerequisites
    runs-on: ubuntu-latest
    outputs:
      current_release: ${{ steps.set-release.outputs.current_release }}
      latest_before: ${{ steps.get-latest.outputs.latest_before }}
      is_patch: ${{ steps.check_patch.outputs.is_patch }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get current release
        id: set-release
        run: |
          release_version="${{ github.event.inputs.version }}"
          echo "Current release: $release_version"
          echo "current_release=$release_version" >> $GITHUB_OUTPUT

      - name: Ensure that release is done from the proper branch
        id: check-branch-name
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          current_release="${{ steps.set-release.outputs.current_release }}"
          echo "Branch name: ${branch}"
          major=$(echo "${current_release}" | cut -d. -f1)
          minor=$(echo "${current_release}" | cut -d. -f2)
          if [ ! "${branch}" == "release-${major}.${minor}" ]; then
            echo "Branch ${branch} is not proper for the release ${current_release}"
            exit 1
          fi

      - name: Check whether image already exists before release
        id: check-whether-image-exists-before-release
        run: |
          image="${{ env.image-name }}:${{ steps.set-release.outputs.current_release }}"
          if docker pull "${image}" >/dev/null 2>&1; then
            echo "Image already exists, which is unexpected before the release"
            exit 2
          fi

      - name: Ensure that sec-scanners-config doesn't contain bdba section
        id: check-sec-scanners-config
        run: |
          cat sec-scanners-config.yaml
          if grep -q bdba sec-scanners-config.yaml; then
            echo "sec-scanners-config file contains bdba section, which would leak into OCM manifest"
            exit 3
          fi

      - name: Check whether release notes exist
        id: check-release-notes
        run: |
          rel_notes_file="docs/release-notes/${{ steps.set-release.outputs.current_release }}.md"
          if [ ! -f "${rel_notes_file}" ]; then
            echo "File with release notes ${rel_notes_file} does not exist"
            exit 4
          fi

      - name: Get latest release before releasing
        id: get-latest
        run: |
          LATEST=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | grep '"tag_name"' | cut -d '"' -f 4)
          echo "Latest release before releasing: $LATEST"
          echo "latest_before=$LATEST" >> $GITHUB_OUTPUT

      - name: Determine if this is a patch release
        id: check_patch
        run: |
          if [[ "${{ steps.set-release.outputs.current_release }}" =~ ^[0-9]+\.[0-9]+\.[1-9][0-9]*$ ]]; then
            echo "is_patch=true" >> $GITHUB_OUTPUT
          else
            echo "is_patch=false" >> $GITHUB_OUTPUT
          fi

  build-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    needs: [check-prerequisites]
    with:
      name: api-gateway/releases/api-gateway-manager
      dockerfile: Dockerfile
      context: .
      build-args: |
        VERSION=${{ needs.check-prerequisites.outputs.current_release }}
      tags: "${{ needs.check-prerequisites.outputs.current_release }}"

  get-image:
    name: Get api-gateway image
    runs-on: ubuntu-latest
    #needs: [ build-image, check-prerequisites ]
    needs: [ check-prerequisites ]
    outputs:
      image: "${{ steps.get-image.outputs.image }}"
    steps:
      - id: get-image
        name: get image
        shell: bash
        run: |
          #image="${{ env.image-name }}:${{ needs.check-prerequisites.outputs.current_release }}"
          image="${{ env.image-name }}:3.4.1"
          echo "image=${image}"
          echo "image=${image}" >> $GITHUB_OUTPUT
      - id: check-image
        name: check whether image exists
        shell: bash
        run: docker pull "${{ steps.get-image.outputs.image }}"

  #############################################
  #
  # Unit tests
  #
  #############################################

  unit-tests:
    name: Unit, integration tests & lint
    needs: [ get-image ]
    uses: ./.github/workflows/call-unit-lint.yaml
    secrets: inherit

  #############################################
  #
  # E2E tests
  # Run on: AWS, K3D
  #
  #############################################

  e2e-tests-k3d:
    name: E2E tests K3D
    runs-on: ubuntu-latest
    needs: [ get-image ]
    strategy:
      fail-fast: false
      matrix:
        test_make_target: [ "test-integration-ory", "test-integration-istio", "test-integration-v2alpha1", "test-integration-gateway", "test-integration-rate-limit", "test-integration-v2" ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/e2e-test-k3d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manager_image: ${{ needs.get-image.outputs.image }}
          test_client_id: ${{ secrets.CLIENT_ID }}
          test_client_secret: ${{ secrets.CLIENT_SECRET }}
          test_oidc_well_known_url: "${{ secrets.OIDC_ISSUER_URL }}/.well-known/openid-configuration"
          test_make_target: ${{ matrix.test_make_target }}

  e2e-tests-aws:
    name: E2E tests AWS
    runs-on: ubuntu-latest
    needs: [ get-image ]
    strategy:
      fail-fast: false
      matrix:
        test_make_target: [ "test-integration-ory", "test-integration-istio", "test-integration-v2alpha1", "test-integration-gateway", "test-integration-rate-limit", "test-integration-v2" ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/e2e-test-gardener
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APIGATEWAY_ACCESS_SIG_BASE64: ${{ secrets.GARDENER_APIRULE_ACCESS }}
        with:
          manager_image: ${{ needs.get-image.outputs.image }}
          gardener_secret: ${{ secrets.GARDENER_TOKEN }}
          gardener_project_name: ${{ vars.GARDENER_PROJECT_NAME }}
          gardener_provider: aws
          test_client_id: ${{ secrets.CLIENT_ID }}
          test_client_secret: ${{ secrets.CLIENT_SECRET }}
          test_oidc_well_known_url: "${{ secrets.OIDC_ISSUER_URL }}/.well-known/openid-configuration"
          test_make_target: ${{ matrix.test_make_target }}

  #############################################
  #
  # Zero downtime tests
  # Run on: AWS, K3D
  #
  #############################################

  migration-downtime-tests-k3d:
    name: Zero Downtime Migration Tests
    runs-on: ubuntu-latest
    needs: [ get-image ]
    strategy:
      fail-fast: false
      matrix:
        handler: [ "no_auth", "allow", "noop", "jwt", "oauth2_introspection" ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/e2e-test-k3d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HANDLER: ${{ matrix.handler }}
        with:
          manager_image: ${{ needs.get-image.outputs.image }}
          test_make_target: test-migration-zero-downtime-${{ matrix.handler }}

  migration-downtime-tests-aws:
    name: Zero Downtime Migration Tests AWS
    runs-on: ubuntu-latest
    needs: [ get-image ]
    strategy:
      fail-fast: false
      matrix:
        handler: [ "no_auth", "allow", "noop", "jwt", "oauth2_introspection" ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/e2e-test-gardener
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APIGATEWAY_ACCESS_SIG_BASE64: ${{ secrets.GARDENER_APIRULE_ACCESS }}
        with:
          manager_image: ${{ needs.get-image.outputs.image }}
          gardener_secret: ${{ secrets.GARDENER_TOKEN }}
          gardener_project_name: ${{ vars.GARDENER_PROJECT_NAME }}
          gardener_provider: aws
          test_client_id: ${{ secrets.CLIENT_ID }}
          test_client_secret: ${{ secrets.CLIENT_SECRET }}
          test_oidc_well_known_url: "${{ secrets.OIDC_ISSUER_URL }}/.well-known/openid-configuration"
          test_make_target: test-migration-zero-downtime-${{ matrix.handler }}

  #############################################
  #
  # Upgrade tests
  # Run on: K3D
  #
  #############################################

  upgrade-tests-k3d:
    name: Upgrade tests
    runs-on: ubuntu-latest
    needs: [ get-image ]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/upgrade-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manager_image: ${{ needs.get-image.outputs.image }}
          test_client_id: ${{ secrets.CLIENT_ID }}
          test_client_secret: ${{ secrets.CLIENT_SECRET }}
          test_oidc_well_known_url: "${{ secrets.OIDC_ISSUER_URL }}/.well-known/openid-configuration"
          target_branch: ${{github.ref_name}}

  #############################################
  #
  # Custom domain tests
  # Run on: AWS, GCP
  #
  #############################################

  e2e-custom-domain-gcp:
    name: E2E custom domain tests GCP
    runs-on: ubuntu-latest
    needs: [ get-image ]
    strategy:
      fail-fast: false
      matrix:
        test_make_target: [ "test-custom-domain", "test-integration-gateway" ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/e2e-test-gardener
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APIGATEWAY_ACCESS_SIG_BASE64: ${{ secrets.GARDENER_APIRULE_ACCESS }}
        with:
          manager_image: ${{ needs.get-image.outputs.image }}
          gardener_secret: ${{ secrets.GARDENER_TOKEN }}
          gardener_project_name: ${{ vars.GARDENER_PROJECT_NAME }}
          gardener_provider: gcp
          test_client_id: ${{ secrets.CLIENT_ID }}
          test_client_secret: ${{ secrets.CLIENT_SECRET }}
          test_oidc_well_known_url: "${{ secrets.OIDC_ISSUER_URL }}/.well-known/openid-configuration"
          dns_secret_json: ${{ secrets.DNS_SECRET_JSON }}
          test_make_target: ${{ matrix.test_make_target }}
          test_custom_domain: ${{ vars.TEST_CUSTOM_DOMAIN }}

  e2e-custom-domain-aws:
    name: E2E custom domain tests AWS
    runs-on: ubuntu-latest
    needs: [ get-image ]
    strategy:
      fail-fast: false
      matrix:
        test_make_target: [ "test-custom-domain", "test-integration-gateway" ]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/e2e-test-gardener
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APIGATEWAY_ACCESS_SIG_BASE64: ${{ secrets.GARDENER_APIRULE_ACCESS }}
        with:
          manager_image: ${{ needs.get-image.outputs.image }}
          gardener_secret: ${{ secrets.GARDENER_TOKEN }}
          gardener_project_name: ${{ vars.GARDENER_PROJECT_NAME }}
          gardener_provider: aws
          test_client_id: ${{ secrets.CLIENT_ID }}
          test_client_secret: ${{ secrets.CLIENT_SECRET }}
          test_oidc_well_known_url: "${{ secrets.OIDC_ISSUER_URL }}/.well-known/openid-configuration"
          dns_secret_json: ${{ secrets.DNS_SECRET_JSON }}
          test_make_target: ${{ matrix.test_make_target }}
          test_custom_domain: ${{ vars.TEST_CUSTOM_DOMAIN }}

  ## CONTINUE IF TESTS ARE GREEN

  create-draft:
    name: Create draft release
    runs-on: ubuntu-latest
    needs: [ check-prerequisites ]
    #needs: [check-prerequisites, build-image, unit-tests, e2e-tests-k3d, e2e-tests-aws, upgrade-tests-k3d, e2e-custom-domain-gcp, e2e-custom-domain-aws, migration-downtime-tests-k3d, migration-downtime-tests-aws ]
    outputs:
      release_id: ${{ steps.create-draft.outputs.release_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE: ${{ needs.check-prerequisites.outputs.current_release }}
        run: ./scripts/create_changelog.sh $RELEASE

      - name: Create draft release
        id: create-draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_ID=$(./scripts/create_draft_release.sh ${{ needs.check-prerequisites.outputs.current_release }})
          echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT

      - name: Create lightweight tag
        run: |
          git tag ${{ needs.check-prerequisites.outputs.current_release }}
          git push origin ${{ needs.check-prerequisites.outputs.current_release }}

  publish-release:
    name: Publish release
    needs: [create-draft, check-prerequisites]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Publish release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/publish_assets.sh ${{ needs.check-prerequisites.outputs.current_release }} ${{ needs.create-draft.outputs.release_id }}

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/publish_release.sh ${{ needs.create-draft.outputs.release_id }}

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [check-prerequisites, publish-release]
    if: success()
    steps:
      - name: Notify
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52
        with:
          webhook: ${{ secrets.SLACK_RELEASE_WEBHOOK }}
          webhook-type: webhook-trigger
          payload-templated: true
          payload: |
            repository: ${{ github.repository }},
            release: ${{ needs.check-prerequisites.outputs.current_release }}

  post-release-adjustments:
    name: Post-Release adjustments
    runs-on: ubuntu-latest
    needs: [check-prerequisites, publish-release]
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GOAT_BOT_REPO_ACCESS }}
          
      - name: Adjust latest tag if needed
        if: ${{ needs.check-prerequisites.outputs.is_patch == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LATEST_BEFORE: ${{ needs.check-prerequisites.outputs.latest_before }}
          CURRENT_RELEASE: ${{ needs.check-prerequisites.outputs.current_release }}
        run: |
          if [ "$(printf '%s\n' "$CURRENT_RELEASE" "$LATEST_BEFORE" | sort -V | head -n1)" = "$CURRENT_RELEASE" ]; then 
            echo "$LATEST_BEFORE should be marked as latest release"
            RELEASE_ID=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              https://api.github.com/repos/${{ github.repository }}/releases/tags/${LATEST_BEFORE} | jq -r '.id')

            curl -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID \
              -d '{"make_latest":"true"}'
          else
            echo "No action needed: $CURRENT_RELEASE is the latest"
          fi

      - name: Update Dependabot for major/minor releases
        if: ${{ needs.check-prerequisites.outputs.is_patch == 'false' }}
        env:
          GH_TOKEN: ${{ secrets.GOAT_BOT_REPO_ACCESS }}
          CURRENT_RELEASE: ${{ needs.check-prerequisites.outputs.current_release }}
          USERNAME: ${{ vars.ACTIONS_BOT_NAME }}
          EMAIL: ${{ vars.ACTIONS_BOT_EMAIL }}
        run: |
          git config user.name "$USERNAME"
          git config user.email "$EMAIL"

          git checkout -b dependabot-config/$CURRENT_RELEASE
          git fetch origin
          git reset --hard origin/main

          MAJOR_MINOR=$(echo $CURRENT_RELEASE | grep -Eo '^[0-9]+\.[0-9]+')
          sed -i "s|release\-.*|release\-$MAJOR_MINOR\"|g" .github/dependabot.yml
          git add .
          if git diff-index --quiet HEAD; then
            echo "Error: No changes detected"
            exit 1
          fi
          git commit -m "update dependabot.yml" -m "Generated by GitHub Actions"
          git push -f -u origin dependabot-config/$CURRENT_RELEASE
          gh pr create --base main --head dependabot-config/$CURRENT_RELEASE --fill || true 
